name: Caller-Workflow
on:
  workflow_dispatch:

jobs:
  call-Code-Quality-Checks-Common-Template:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses:  GitHubActions-POC/Reusable-Templates/.github/workflows/Code-Quality-check.yml@main
    with:
      GLOBAL_MY_MAPPED_ENV_VAR: staticvar
      output: results.sarif
      format: sarif
      code-quality: no 
    secrets:
      ADOVARIABLE: "${{ secrets.ADOVARIABLE }}" 
  call-Junits-Common-Template:
    permissions: 
      contents: read
      issues: read
      checks: write
      pull-requests: write
    uses:  GitHubActions-POC/Reusable-Templates/.github/workflows/Junits.yml@main
    with:
      GLOBAL_MY_MAPPED_ENV_VAR: staticvar
      junit_files: "**/surefire-reports/TEST-*.xml"
      junit: no 
    secrets:
      ADOVARIABLE: "${{ secrets.ADOVARIABLE }}"      
  call-Maven-Build-Common-Template:
    uses:  GitHubActions-POC/Reusable-Templates/.github/workflows/Maven-Build.yml@main
    with:
      GLOBAL_MY_MAPPED_ENV_VAR: staticvar
      package: pom.xml
    secrets:
      ADOVARIABLE: "${{ secrets.ADOVARIABLE }}" 
  call-Artifact-Download-Common-Template:
    needs: call-Maven-Build-Common-Template
    if: (needs.call-Maven-Build-Common-Template.result == 'success')
    uses:  GitHubActions-POC/Reusable-Templates/.github/workflows/Artifact-Reusable-workflow.yml@main   
  call-Artifact-deploy-Common-Template:
    needs: call-Artifact-Download-Common-Template
    if: (needs.call-Artifact-Download-Common-Template.result == 'success')
    uses:  GitHubActions-POC/Reusable-Templates/.github/workflows/Deploy.yml@main
    secrets:
      CLIENT_ID: "${{ secrets.CLIENT_ID }}"
      CLIENT_SECRET: "${{ secrets.CLIENT_SECRET }}"
      SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"
      TENANT_ID: "${{ secrets.TENANT_ID }}"
  
 
      
